/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
import spock.lang.Specification

class HelloTest extends Specification {
    def "Hello Greets"() {
        setup:
        def subject = new Hello()

        when:
        def result = subject.greet("Sam")

        then:
        result == "Hello, Sam."
    }
}
